### ISSUE TITLE
Improved build

### ISSUE THREAD

**Issue by antoine-bussy** [godefv/math#1]
Possible improvements:
- [x] CMake-enforced build requirements
  - [x] GCC >= 7
  - [x] Boost >= 1.61 (hana)
- [x] enable warnings

IMO, the GCC check is mandatory since the library won't compile with GCC 6.3 and errors are cryptic.

I've fixed these in a branch, but don't have the permission to push.
For warnings, I used http://www.artificialworlds.net/blog/2014/07/18/best-gcc-warning-flags-for-compiling-c/. Might be a bit too much, but since the project is young... :)

**Comment by godefv** [comment]
fait
